# Generated by Django 3.2.7 on 2021-09-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=250, verbose_name="libellé de l'intervention")),
                ('description', models.TextField(verbose_name="description de l'intervention")),
                ('agent_name', models.CharField(max_length=120, verbose_name="nom de l'intervenant")),
                ('city', models.CharField(max_length=350, verbose_name="lieu de l'intervention")),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='intervention créée le')),
                ('date', models.DateField(verbose_name="date de l'intervention")),
                ('status', models.CharField(choices=[('Brouillon', 'Brouillon'), ('Validé', 'Validé'), ('Terminé', 'Terminé')], default='Brouillon', max_length=25, verbose_name="statu de l'intervention")),
                ('edit', models.BooleanField(default=True, verbose_name="modification de l'intervention")),
            ],
        ),
    ]
