# Generated by Django 3.2.7 on 2021-10-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='create_at',
            field=models.DateTimeField(verbose_name='intervention créée le'),
        ),
    ]
