# Generated by Django 3.2.7 on 2021-10-04 06:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_intervention_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='intervention créée le'),
        ),
    ]
